import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const VERIFIED_DATA = [
  {
    slug: 'the-carlton',
    tier: 'Ultra Luxury Premium',
    score: 'Luxury',
    facilities: [
      { name: 'Parking', category: 'POPULAR AMENITIES' },
      { name: 'Jacuzzi', category: 'POPULAR AMENITIES' },
      { name: 'Spa', category: 'POPULAR AMENITIES' },
      { name: 'Gym', category: 'POPULAR AMENITIES' },
      { name: 'Housekeeping', category: 'BASIC FACILITIES' },
      { name: 'Wi-Fi', category: 'BASIC FACILITIES' },
      { name: 'Express check-in/check-out', category: 'BASIC FACILITIES' },
      { name: 'Smoking Rooms', category: 'BASIC FACILITIES' },
      { name: 'Elevator/Lift', category: 'BASIC FACILITIES' },
      { name: 'Umbrellas', category: 'BASIC FACILITIES' },
      { name: 'Refrigerator', category: 'BASIC FACILITIES' },
      { name: 'Ironing Service', category: 'BASIC FACILITIES' },
      { name: 'Newspaper', category: 'BASIC FACILITIES' },
      { name: 'Air Conditioning', category: 'BASIC FACILITIES' },
      { name: 'Central Heating', category: 'BASIC FACILITIES' },
      { name: 'LAN', category: 'BASIC FACILITIES' },
      { name: 'Laundry Service', category: 'BASIC FACILITIES' },
      { name: 'Smoke Detector', category: 'BASIC FACILITIES' },
      { name: 'Laundromat', category: 'BASIC FACILITIES' },
      { name: 'Room Service', category: 'BASIC FACILITIES' },
      { name: 'Power Backup', category: 'BASIC FACILITIES' },
      { name: 'Washing Machine', category: 'BASIC FACILITIES' },
      { name: 'Ticket/Tour Assistance', category: 'GENERAL SERVICES' },
      { name: 'Multilingual Staff', category: 'GENERAL SERVICES' },
      { name: 'Concierge', category: 'GENERAL SERVICES' },
      { name: 'Facilities for Guests with Disabilities', category: 'GENERAL SERVICES' },
      { name: 'Wheelchair', category: 'GENERAL SERVICES' },
      { name: 'Doctor on Call', category: 'GENERAL SERVICES' },
      { name: 'Luggage Assistance', category: 'GENERAL SERVICES' },
      { name: 'First-aid Services', category: 'HEALTH & WELLNESS' },
      { name: 'Shuttle Service', category: 'TRANSFERS' },
      { name: 'Airport Transfers', category: 'TRANSFERS' },
      { name: 'Dining Area', category: 'ROOM AMENITIES' },
      { name: 'Toiletries', category: 'ROOM AMENITIES' },
      { name: 'Mineral Water', category: 'ROOM AMENITIES' },
      { name: 'Interconnected Room', category: 'ROOM AMENITIES' },
      { name: 'Heater', category: 'ROOM AMENITIES' },
      { name: 'Geyser/Water Heater', category: 'ROOM AMENITIES' },
      { name: 'Hairdryer', category: 'ROOM AMENITIES' },
      { name: 'Iron/Ironing Board', category: 'ROOM AMENITIES' },
      { name: 'Work Desk', category: 'ROOM AMENITIES' },
      { name: 'Bubble Bath', category: 'ROOM AMENITIES' },
      { name: 'Sofa', category: 'ROOM AMENITIES' },
      { name: 'Dental Kit', category: 'ROOM AMENITIES' },
      { name: 'Minibar', category: 'ROOM AMENITIES' },
      { name: 'Living Area', category: 'ROOM AMENITIES' },
      { name: 'Bathtub', category: 'ROOM AMENITIES' },
      { name: 'Childcare Services', category: 'FAMILY & KIDS' },
      { name: 'Baby Safety Gates', category: 'FAMILY & KIDS' },
      { name: 'Playground', category: 'FAMILY & KIDS' },
      { name: 'Restaurant', category: 'FOOD & DRINKS' },
      { name: 'Coffee Shop', category: 'FOOD & DRINKS' },
      { name: 'Bar', category: 'FOOD & DRINKS' },
      { name: 'Kids’ Meals', category: 'FOOD & DRINKS' },
      { name: 'Currency Exchange', category: 'PAYMENT SERVICES' },
      { name: 'Fire Extinguishers', category: 'SAFETY & SECURITY' },
      { name: 'Security Alarms', category: 'SAFETY & SECURITY' },
      { name: 'Security Guard', category: 'SAFETY & SECURITY' },
      { name: 'Safe', category: 'SAFETY & SECURITY' },
      { name: 'Electronic Keycard', category: 'SAFETY & SECURITY' },
      { name: 'CCTV', category: 'SAFETY & SECURITY' },
      { name: 'Entertainment', category: 'ENTERTAINMENT' },
      { name: 'TV', category: 'MEDIA & TECHNOLOGY' },
      { name: 'Computer Station', category: 'MEDIA & TECHNOLOGY' },
      { name: 'Facial Treatments', category: 'BEAUTY & SPA' },
      { name: 'Salon', category: 'BEAUTY & SPA' },
      { name: 'Manicure/Pedicure', category: 'BEAUTY & SPA' },
      { name: 'Steam and Sauna', category: 'BEAUTY & SPA' },
      { name: 'Massage', category: 'BEAUTY & SPA' },
      { name: 'Cycling', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Golf', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Bonfire', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Snorkelling', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Golf Course / Mini Golf', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Vehicle Rentals', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Kids Play Area', category: 'INDOOR ACTIVITIES' },
      { name: 'Indoor Games', category: 'INDOOR ACTIVITIES' },
      { name: 'Garden', category: 'COMMON AREA' },
      { name: 'Outdoor Furniture', category: 'COMMON AREA' },
      { name: 'Lounge', category: 'COMMON AREA' },
      { name: 'Reception', category: 'COMMON AREA' },
      { name: 'Balcony/Terrace', category: 'COMMON AREA' },
      { name: 'Library', category: 'COMMON AREA' },
      { name: 'Fireplace', category: 'COMMON AREA' },
      { name: 'Souvenir Shop', category: 'SHOPPING' },
      { name: 'Shops', category: 'SHOPPING' },
      { name: 'Fax Service', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Business Centre', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Photocopying', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Banquet', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Conference Room', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Printer', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Family Rooms', category: 'OTHER FACILITIES' },
      { name: 'Cloak Room', category: 'OTHER FACILITIES' },
      { name: 'Carbon Monoxide Detector', category: 'OTHER FACILITIES' }
    ]
  },
  {
    slug: 'the-tamara-kodai',
    tier: 'Ultra Luxury Premium',
    score: 'Luxury',
    facilities: [
      { name: 'Parking', category: 'POPULAR AMENITIES' },
      { name: 'Spa', category: 'POPULAR AMENITIES' },
      { name: 'Gym', category: 'POPULAR AMENITIES' },
      { name: 'Bonfire', category: 'POPULAR AMENITIES' },
      { name: 'Housekeeping', category: 'BASIC FACILITIES' },
      { name: 'Wi-Fi', category: 'BASIC FACILITIES' },
      { name: 'Swimming Pool', category: 'BASIC FACILITIES' },
      { name: 'LAN', category: 'BASIC FACILITIES' },
      { name: 'Umbrellas', category: 'BASIC FACILITIES' },
      { name: 'Refrigerator', category: 'BASIC FACILITIES' },
      { name: 'Laundry Service', category: 'BASIC FACILITIES' },
      { name: 'Smoke Detector', category: 'BASIC FACILITIES' },
      { name: 'Room Service', category: 'BASIC FACILITIES' },
      { name: 'Power Backup', category: 'BASIC FACILITIES' },
      { name: 'Caretaker', category: 'GENERAL SERVICES' },
      { name: 'Multilingual Staff', category: 'GENERAL SERVICES' },
      { name: 'Concierge', category: 'GENERAL SERVICES' },
      { name: 'Wheelchair', category: 'GENERAL SERVICES' },
      { name: 'Pool/Beach Towels', category: 'GENERAL SERVICES' },
      { name: 'Wheelchair Accessible', category: 'GENERAL SERVICES' },
      { name: 'Doctor on Call', category: 'GENERAL SERVICES' },
      { name: 'Luggage Assistance', category: 'GENERAL SERVICES' },
      { name: 'First-aid Services', category: 'HEALTH & WELLNESS' },
      { name: 'Yoga', category: 'HEALTH & WELLNESS' },
      { name: 'Activity Centre', category: 'HEALTH & WELLNESS' },
      { name: 'Meditation Room', category: 'HEALTH & WELLNESS' },
      { name: 'Shuttle Service', category: 'TRANSFERS' },
      { name: 'Railway Transfers', category: 'TRANSFERS' },
      { name: 'Airport Transfers', category: 'TRANSFERS' },
      { name: 'Bus Station Transfers', category: 'TRANSFERS' },
      { name: 'Dining Area', category: 'ROOM AMENITIES' },
      { name: 'Toiletries', category: 'ROOM AMENITIES' },
      { name: 'Mineral Water', category: 'ROOM AMENITIES' },
      { name: 'Interconnected Room', category: 'ROOM AMENITIES' },
      { name: 'Balcony', category: 'ROOM AMENITIES' },
      { name: 'Heater', category: 'ROOM AMENITIES' },
      { name: 'Geyser/Water Heater', category: 'ROOM AMENITIES' },
      { name: 'Hairdryer', category: 'ROOM AMENITIES' },
      { name: 'Iron/Ironing Board', category: 'ROOM AMENITIES' },
      { name: 'Work Desk', category: 'ROOM AMENITIES' },
      { name: 'Mini Fridge', category: 'ROOM AMENITIES' },
      { name: 'Sofa', category: 'ROOM AMENITIES' },
      { name: 'Dental Kit', category: 'ROOM AMENITIES' },
      { name: 'Minibar', category: 'ROOM AMENITIES' },
      { name: 'Coffee Machine', category: 'ROOM AMENITIES' },
      { name: 'Living Area', category: 'ROOM AMENITIES' },
      { name: 'Bathtub', category: 'ROOM AMENITIES' },
      { name: 'Jacuzzi', category: 'ROOM AMENITIES' },
      { name: 'Restaurant', category: 'FOOD & DRINKS' },
      { name: 'Bar', category: 'FOOD & DRINKS' },
      { name: 'Kid’s Menu', category: 'FOOD & DRINKS' },
      { name: 'Fire Extinguishers', category: 'SAFETY & SECURITY' },
      { name: 'Security Alarms', category: 'SAFETY & SECURITY' },
      { name: 'CCTV', category: 'SAFETY & SECURITY' },
      { name: 'Entertainment', category: 'ENTERTAINMENT' },
      { name: 'TV', category: 'MEDIA & TECHNOLOGY' },
      { name: 'Salon', category: 'BEAUTY & SPA' },
      { name: 'Steam and Sauna', category: 'BEAUTY & SPA' },
      { name: 'Massage', category: 'BEAUTY & SPA' },
      { name: 'Cycling', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Indoor Games Room', category: 'INDOOR ACTIVITIES' },
      { name: 'Indoor Games', category: 'INDOOR ACTIVITIES' },
      { name: 'Garden', category: 'COMMON AREA' },
      { name: 'Living Room', category: 'COMMON AREA' },
      { name: 'Lounge', category: 'COMMON AREA' },
      { name: 'Reception', category: 'COMMON AREA' },
      { name: 'Balcony/Terrace', category: 'COMMON AREA' },
      { name: 'Banquet', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Conference Room', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Kids’ Play Area', category: 'OTHER FACILITIES' },
      { name: 'Cloak Room', category: 'OTHER FACILITIES' }
    ]
  },
  {
    slug: 'sterling-kodai-lake',
    tier: 'Premium Resort',
    score: 'Premium',
    facilities: [
      { name: 'Gym', category: 'POPULAR AMENITIES' },
      { name: 'Jungle Safari', category: 'POPULAR AMENITIES' },
      { name: 'Parking', category: 'POPULAR AMENITIES' },
      { name: 'Bonfire', category: 'POPULAR AMENITIES' },
      { name: 'Housekeeping', category: 'BASIC FACILITIES' },
      { name: 'Wi-Fi', category: 'BASIC FACILITIES' },
      { name: 'Express check-in/check-out', category: 'BASIC FACILITIES' },
      { name: 'Elevator/Lift', category: 'BASIC FACILITIES' },
      { name: 'Umbrellas', category: 'BASIC FACILITIES' },
      { name: 'Refrigerator', category: 'BASIC FACILITIES' },
      { name: 'Laundry Service', category: 'BASIC FACILITIES' },
      { name: 'Smoke Detector', category: 'BASIC FACILITIES' },
      { name: 'Room Service', category: 'BASIC FACILITIES' },
      { name: 'Power Backup', category: 'BASIC FACILITIES' },
      { name: 'Ticket/Tour Assistance', category: 'GENERAL SERVICES' },
      { name: 'Multilingual Staff', category: 'GENERAL SERVICES' },
      { name: 'Concierge', category: 'GENERAL SERVICES' },
      { name: 'Wheelchair', category: 'GENERAL SERVICES' },
      { name: 'Wheelchair Accessible', category: 'GENERAL SERVICES' },
      { name: 'Butler Services', category: 'GENERAL SERVICES' },
      { name: 'Doctor on Call', category: 'GENERAL SERVICES' },
      { name: 'Luggage Assistance', category: 'GENERAL SERVICES' },
      { name: 'First-aid Services', category: 'HEALTH & WELLNESS' },
      { name: 'Activity Centre', category: 'HEALTH & WELLNESS' },
      { name: 'Shuttle Service', category: 'TRANSFERS' },
      { name: 'Airport Transfers', category: 'TRANSFERS' },
      { name: 'Dining Area', category: 'ROOM AMENITIES' },
      { name: 'Mini Fridge', category: 'ROOM AMENITIES' },
      { name: 'Sofa', category: 'ROOM AMENITIES' },
      { name: 'Toiletries', category: 'ROOM AMENITIES' },
      { name: 'Mineral Water', category: 'ROOM AMENITIES' },
      { name: 'Air Conditioning', category: 'ROOM AMENITIES' },
      { name: 'Heater', category: 'ROOM AMENITIES' },
      { name: 'Geyser/Water Heater', category: 'ROOM AMENITIES' },
      { name: 'Hairdryer', category: 'ROOM AMENITIES' },
      { name: 'Living Area', category: 'ROOM AMENITIES' },
      { name: 'Iron/Ironing Board', category: 'ROOM AMENITIES' },
      { name: 'Work Desk', category: 'ROOM AMENITIES' },
      { name: 'Kids’ Club', category: 'FAMILY & KIDS' },
      { name: 'Playground', category: 'FAMILY & KIDS' },
      { name: 'Restaurant', category: 'FOOD & DRINKS' },
      { name: 'Breakfast', category: 'FOOD & DRINKS' },
      { name: 'Bar', category: 'FOOD & DRINKS' },
      { name: 'Veg Food Available', category: 'FOOD & DRINKS' },
      { name: 'Barbeque', category: 'FOOD & DRINKS' },
      { name: 'Kid’s Menu', category: 'FOOD & DRINKS' },
      { name: 'Fire Extinguishers', category: 'SAFETY & SECURITY' },
      { name: 'Security Alarms', category: 'SAFETY & SECURITY' },
      { name: 'Security Guard', category: 'SAFETY & SECURITY' },
      { name: 'CCTV', category: 'SAFETY & SECURITY' },
      { name: 'Entertainment', category: 'ENTERTAINMENT' },
      { name: 'Professional Photography', category: 'ENTERTAINMENT' },
      { name: 'Karaoke', category: 'ENTERTAINMENT' },
      { name: 'Music System', category: 'ENTERTAINMENT' },
      { name: 'Electrical Adapters', category: 'MEDIA & TECHNOLOGY' },
      { name: 'Spa', category: 'BEAUTY & SPA' },
      { name: 'Steam and Sauna', category: 'BEAUTY & SPA' },
      { name: 'Massage', category: 'BEAUTY & SPA' },
      { name: 'Cycling', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Indoor Games Room', category: 'INDOOR ACTIVITIES' },
      { name: 'Kids Play Area', category: 'INDOOR ACTIVITIES' },
      { name: 'Indoor Games', category: 'INDOOR ACTIVITIES' },
      { name: 'Table Tennis', category: 'INDOOR ACTIVITIES' },
      { name: 'Garden', category: 'COMMON AREA' },
      { name: 'Outdoor Furniture', category: 'COMMON AREA' },
      { name: 'Living Room', category: 'COMMON AREA' },
      { name: 'Reception', category: 'COMMON AREA' },
      { name: 'Balcony/Terrace', category: 'COMMON AREA' },
      { name: 'Library', category: 'COMMON AREA' },
      { name: 'Souvenir Shop', category: 'SHOPPING' },
      { name: 'Business Centre', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Photocopying', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Banquet', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Conference Room', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Printer', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Pet Bowls', category: 'PET ESSENTIALS' },
      { name: 'Pet Baskets', category: 'PET ESSENTIALS' },
      { name: 'EV Charging Station', category: 'OTHER FACILITIES' },
      { name: 'Kids’ Play Area', category: 'OTHER FACILITIES' },
      { name: 'Cloak Room', category: 'OTHER FACILITIES' }
    ]
  },
  {
    slug: 'hotel-kodai-international',
    tier: 'Upper Midscale',
    score: 'Premium',
    facilities: [
      { name: 'Gym', category: 'POPULAR AMENITIES' },
      { name: 'Parking', category: 'POPULAR AMENITIES' },
      { name: 'Bonfire', category: 'POPULAR AMENITIES' },
      { name: 'Indoor Games', category: 'POPULAR AMENITIES' },
      { name: 'Housekeeping', category: 'BASIC FACILITIES' },
      { name: 'Newspaper', category: 'BASIC FACILITIES' },
      { name: 'Wi-Fi', category: 'BASIC FACILITIES' },
      { name: 'Umbrellas', category: 'BASIC FACILITIES' },
      { name: 'Laundry Service', category: 'BASIC FACILITIES' },
      { name: 'Smoke Detector', category: 'BASIC FACILITIES' },
      { name: 'Room Service', category: 'BASIC FACILITIES' },
      { name: 'Power Backup', category: 'BASIC FACILITIES' },
      { name: 'Multilingual Staff', category: 'GENERAL SERVICES' },
      { name: 'Concierge', category: 'GENERAL SERVICES' },
      { name: 'Facilities for Guests with Disabilities', category: 'GENERAL SERVICES' },
      { name: 'Wheelchair', category: 'GENERAL SERVICES' },
      { name: 'Doctor on Call', category: 'GENERAL SERVICES' },
      { name: 'Luggage Assistance', category: 'GENERAL SERVICES' },
      { name: 'First-aid Services', category: 'HEALTH & WELLNESS' },
      { name: 'Shuttle Service', category: 'TRANSFERS' },
      { name: 'Airport Transfers', category: 'TRANSFERS' },
      { name: 'Sofa', category: 'ROOM AMENITIES' },
      { name: 'Toiletries', category: 'ROOM AMENITIES' },
      { name: 'Mineral Water', category: 'ROOM AMENITIES' },
      { name: 'Interconnected Room', category: 'ROOM AMENITIES' },
      { name: 'Balcony', category: 'ROOM AMENITIES' },
      { name: 'Dental Kit', category: 'ROOM AMENITIES' },
      { name: 'Heater', category: 'ROOM AMENITIES' },
      { name: 'Geyser/Water Heater', category: 'ROOM AMENITIES' },
      { name: 'Hairdryer', category: 'ROOM AMENITIES' },
      { name: 'Iron/Ironing Board', category: 'ROOM AMENITIES' },
      { name: 'Work Desk', category: 'ROOM AMENITIES' },
      { name: 'Dining Area', category: 'FOOD & DRINKS' },
      { name: 'Restaurant', category: 'FOOD & DRINKS' },
      { name: 'Bar', category: 'FOOD & DRINKS' },
      { name: 'Kid’s Menu', category: 'FOOD & DRINKS' },
      { name: 'CCTV', category: 'SAFETY & SECURITY' },
      { name: 'TV', category: 'MEDIA & TECHNOLOGY' },
      { name: 'Spa', category: 'BEAUTY & SPA' },
      { name: 'Steam and Sauna', category: 'BEAUTY & SPA' },
      { name: 'Massage', category: 'BEAUTY & SPA' },
      { name: 'Golf Course / Mini Golf', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Outdoor Sports', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Garden', category: 'COMMON AREA' },
      { name: 'Reception', category: 'COMMON AREA' },
      { name: 'Fax Service', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Business Centre', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Photocopying', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Banquet', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Conference Room', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Printer', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Medical Centre', category: 'OTHER FACILITIES' },
      { name: 'Kids’ Play Area', category: 'OTHER FACILITIES' },
      { name: 'Cloak Room', category: 'OTHER FACILITIES' }
    ]
  },
  {
    slug: 'le-poshe-by-sparsa',
    tier: 'Premium Resort',
    score: 'Premium',
    facilities: [
      { name: 'Parking', category: 'POPULAR AMENITIES' },
      { name: 'Spa', category: 'POPULAR AMENITIES' },
      { name: 'Gym', category: 'POPULAR AMENITIES' },
      { name: 'Bonfire', category: 'POPULAR AMENITIES' },
      { name: 'Housekeeping', category: 'BASIC FACILITIES' },
      { name: 'Newspaper', category: 'BASIC FACILITIES' },
      { name: 'Wi-Fi', category: 'BASIC FACILITIES' },
      { name: 'Smoking Rooms', category: 'BASIC FACILITIES' },
      { name: 'Elevator/Lift', category: 'BASIC FACILITIES' },
      { name: 'Umbrellas', category: 'BASIC FACILITIES' },
      { name: 'Laundry Service', category: 'BASIC FACILITIES' },
      { name: 'Smoke Detector', category: 'BASIC FACILITIES' },
      { name: 'Room Service', category: 'BASIC FACILITIES' },
      { name: 'Power Backup', category: 'BASIC FACILITIES' },
      { name: 'Activity Centre', category: 'BASIC FACILITIES' },
      { name: 'Caretaker', category: 'GENERAL SERVICES' },
      { name: 'Multilingual Staff', category: 'GENERAL SERVICES' },
      { name: 'Concierge', category: 'GENERAL SERVICES' },
      { name: 'Facilities for Guests with Disabilities', category: 'GENERAL SERVICES' },
      { name: 'Wheelchair', category: 'GENERAL SERVICES' },
      { name: 'Doctor on Call', category: 'GENERAL SERVICES' },
      { name: 'Luggage Assistance', category: 'GENERAL SERVICES' },
      { name: 'First-aid Services', category: 'HEALTH & WELLNESS' },
      { name: 'Yoga', category: 'HEALTH & WELLNESS' },
      { name: 'Shuttle Service', category: 'TRANSFERS' },
      { name: 'Pickup/Drop', category: 'TRANSFERS' },
      { name: 'Railway Transfers', category: 'TRANSFERS' },
      { name: 'Airport Transfers', category: 'TRANSFERS' },
      { name: 'Bus Station Transfers', category: 'TRANSFERS' },
      { name: 'Sofa', category: 'ROOM AMENITIES' },
      { name: 'Dining Area', category: 'ROOM AMENITIES' },
      { name: 'Mini Fridge', category: 'ROOM AMENITIES' },
      { name: 'Toiletries', category: 'ROOM AMENITIES' },
      { name: 'Dental Kit', category: 'ROOM AMENITIES' },
      { name: 'Heater', category: 'ROOM AMENITIES' },
      { name: 'Minibar', category: 'ROOM AMENITIES' },
      { name: 'Geyser/Water Heater', category: 'ROOM AMENITIES' },
      { name: 'Hairdryer', category: 'ROOM AMENITIES' },
      { name: 'Coffee Machine', category: 'ROOM AMENITIES' },
      { name: 'Living Area', category: 'ROOM AMENITIES' },
      { name: 'Iron/Ironing Board', category: 'ROOM AMENITIES' },
      { name: 'Work Desk', category: 'ROOM AMENITIES' },
      { name: 'Kids’ Club', category: 'FAMILY & KIDS' },
      { name: 'Restaurant', category: 'FOOD & DRINKS' },
      { name: 'Cooking Class', category: 'FOOD & DRINKS' },
      { name: 'Kid’s Menu', category: 'FOOD & DRINKS' },
      { name: 'Fire Extinguishers', category: 'SAFETY & SECURITY' },
      { name: 'Security Alarms', category: 'SAFETY & SECURITY' },
      { name: 'Security Guard', category: 'SAFETY & SECURITY' },
      { name: 'CCTV', category: 'SAFETY & SECURITY' },
      { name: 'Entertainment', category: 'ENTERTAINMENT' },
      { name: 'Music System', category: 'ENTERTAINMENT' },
      { name: 'TV', category: 'MEDIA & TECHNOLOGY' },
      { name: 'Salon', category: 'BEAUTY & SPA' },
      { name: 'Steam and Sauna', category: 'BEAUTY & SPA' },
      { name: 'Massage', category: 'BEAUTY & SPA' },
      { name: 'Outdoor Sports', category: 'OUTDOOR ACTIVITIES & SPORTS' },
      { name: 'Indoor Games Room', category: 'INDOOR ACTIVITIES' },
      { name: 'Indoor Games', category: 'INDOOR ACTIVITIES' },
      { name: 'Garden', category: 'COMMON AREA' },
      { name: 'Outdoor Furniture', category: 'COMMON AREA' },
      { name: 'Living Room', category: 'COMMON AREA' },
      { name: 'Lounge', category: 'COMMON AREA' },
      { name: 'Reception', category: 'COMMON AREA' },
      { name: 'Balcony/Terrace', category: 'COMMON AREA' },
      { name: 'Souvenir Shop', category: 'SHOPPING' },
      { name: 'Photocopying', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Banquet', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Conference Room', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Printer', category: 'BUSINESS CENTER & CONFERENCES' },
      { name: 'Medical Centre', category: 'OTHER FACILITIES' },
      { name: 'EV Charging Station', category: 'OTHER FACILITIES' },
      { name: 'Kids’ Play Area', category: 'OTHER FACILITIES' },
      { name: 'Cloak Room', category: 'OTHER FACILITIES' },
      { name: 'Auditory Guidance', category: 'OTHER FACILITIES' }
    ]
  }
];

async function seedFacilities() {
  console.log('🏨 Seeding verified facility data...');

  const hotels = await prisma.hotel.findMany({ select: { id: true, name: true, slug: true } });

  let totalDeleted = 0;
  let totalCreated = 0;

  for (const hotel of hotels) {
    const data = VERIFIED_DATA.find(d => d.slug === hotel.slug);
    if (!data) {
      console.warn(`  ⚠️  No facility data defined for ${hotel.name} (${hotel.slug})`);
      continue;
    }

    // Update Hotel Luxury Tier and Score
    await prisma.hotel.update({
      where: { id: hotel.id },
      data: {
        luxuryTier: data.tier,
        facilityScore: data.score
      }
    });

    // Delete existing facilities for this hotel
    const deleted = await prisma.facility.deleteMany({ where: { hotelId: hotel.id } });
    totalDeleted += deleted.count;

    // Insert verified facilities
    // Remove duplicates explicitly
    const uniqueFacilities = Array.from(new Map(data.facilities.map(item => [item.name, item])).values());
    for (const fac of uniqueFacilities) {
      await prisma.facility.create({
        data: {
          hotelId: hotel.id,
          normalizedKey: fac.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
          name: fac.name,
          category: fac.category,
          available: true,
          quality: data.score === 'Luxury' ? 5 : (data.score === 'Premium' ? 4 : 3),
        },
      });
      totalCreated++;
    }

    console.log(`  ✓  ${hotel.name}: updated tier to ${data.tier}, ${uniqueFacilities.length} facilities seeded`);
  }

  console.log(`\\n✅ Done. Deleted ${totalDeleted} old records. Created ${totalCreated} verified facility entries.`);
}

seedFacilities()
  .catch(e => { console.error('Seed failed:', e); process.exit(1); })
  .finally(() => prisma.$disconnect());
